import { useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, Search, CheckCircle2, AlertCircle, Clock3, CalendarDays } from "lucide-react";
import { apiFetch } from "../lib/api";
import { statusLabel, type DateRequirement } from "./AttendanceRequirements";
import "./AttendanceReport.css";
type Member={id:number;name:string;login:string;dates:DateRequirement[];due:number;met:number;missing:number;review:number;below:number;required_minutes:number;recorded_minutes:number;percent:number|null;hour_percent:number|null;error?:string;synced?:string};
const hours=(m:number)=>`${Math.floor(m/60)}h ${m%60}m`;
export default function AttendanceReport({revision}:{revision:number}){
 const [month,setMonth]=useState(()=>{const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Bahrain",year:"numeric",month:"2-digit"}).formatToParts(new Date());return p.find(v=>v.type==="year")!.value+"-"+p.find(v=>v.type==="month")!.value});
 const [members,setMembers]=useState<Member[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [query,setQuery]=useState("");const [filter,setFilter]=useState("all");
 useEffect(()=>{const c=new AbortController();setLoading(true);setError("");setMembers([]);apiFetch("/admin/attendance/report?month="+month,{signal:c.signal,headers:{Authorization:"Bearer "+localStorage.getItem("jwt")}}).then(v=>{if(!c.signal.aborted)setMembers(v.members)}).catch(e=>{if(!c.signal.aborted)setError(e.message)}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[month,revision]);
 function move(n:number){const [y,m]=month.split("-").map(Number);setMonth(new Date(Date.UTC(y,m-1+n,1)).toISOString().slice(0,7))}
 const valid=members.filter(m=>!m.error);const due=valid.reduce((n,m)=>n+m.due,0);const met=valid.reduce((n,m)=>n+m.met,0);const attention=valid.filter(m=>m.missing+m.below+m.review>0).length;
 const shown=members.filter(m=>(m.name+" "+m.login).toLowerCase().includes(query.toLowerCase())&&(filter==="all"||filter==="attention"&&m.missing+m.review+m.below>0||filter==="missing"&&m.missing>0||filter==="met"&&m.percent===100||filter==="unavailable"&&!!m.error||filter==="unassigned"&&!m.dates.length));
 return <section className="monthly-attendance-report"><header><div><span className="mar-eyebrow">MANDATORY ATTENDANCE</span><h2>Monthly attendance</h2><p>Required dates, recorded hours and members who need follow-up.</p></div><div className="mar-month"><button aria-label="Previous attendance report month" onClick={()=>move(-1)}><ChevronLeft size={17}/></button><input type="month" aria-label="Attendance report month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/><button aria-label="Next attendance report month" onClick={()=>move(1)}><ChevronRight size={17}/></button></div></header>
 {error?<p role="alert">{error}</p>:<><div className="mar-metrics"><div><strong>{loading?"—":members.length}</strong><span>Enrolled members</span></div><div><strong>{loading||!due?"—":Math.round(met/due*100)+"%"}</strong><span>Required dates met</span></div><div><strong>{loading?"—":attention}</strong><span>Need attention</span></div><div><strong>{loading?"—":valid.reduce((n,m)=>n+m.missing,0)}</strong><span>Dates with no record</span></div></div>
 <p className="mar-note">Percentages cover assigned dates before today in Bahrain. Today and future dates are excluded. Missing records need review, not automatic absence. BioTime data is cached for up to 2 hours.</p>
 {members.some(m=>m.error)&&<p role="alert" className="mar-warning">{members.filter(m=>m.error).length} members could not be checked and are excluded from totals.</p>}
 <div className="mar-filters"><label><Search size={16}/><input aria-label="Search attendance members" placeholder="Search name or username…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter attendance report" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All members</option><option value="attention">Needs attention</option><option value="missing">No attendance record</option><option value="met">All due dates met</option><option value="unavailable">Data unavailable</option><option value="unassigned">No assigned dates</option></select></div>
 {loading?<p role="status">Checking monthly attendance…</p>:!shown.length?<p>No members match this view.</p>:<div className="mar-members">{shown.map(m=><details key={m.id}><summary><div className="mar-person"><strong>{m.name}</strong><small>@{m.login}</small></div><div className="mar-progress"><strong>{m.error?"Unavailable":m.percent===null?"Not due":Math.round(m.percent)+"%"}</strong><progress max="100" value={m.percent??0} aria-label={m.name+" required dates met"}/><small>{m.met} / {m.due} due dates met</small></div><div><strong>{m.error?"—":hours(m.recorded_minutes)}</strong><small>of {hours(m.required_minutes)} required</small></div><span className={"mar-status "+(m.missing+m.review+m.below?"attention":"")}>{m.error?"Check connection":!m.dates.length?"No requirements":m.missing+m.review+m.below?`${m.missing+m.review+m.below} need review`:m.due?"On target":"Upcoming"}</span></summary><div className="mar-detail">
 {m.error?<p role="alert">{m.error}</p>:<div className="mar-detail-overview"><div className="mar-detail-chips"><span className="mar-chip rose"><AlertCircle size={14}/><b>{m.below}</b> below target</span><span className="mar-chip amber"><CalendarDays size={14}/><b>{m.missing}</b> no record</span><span className="mar-chip neutral"><Clock3 size={14}/><b>{m.review}</b> incomplete</span></div><div className="mar-hour-score"><span>Hours completion</span><strong>{m.hour_percent===null?"Not due":Math.round(m.hour_percent)+"%"}</strong></div></div>}
 <div className="mar-table-wrap"><table className="mar-days-table"><thead><tr><th>Date</th><th>Recorded</th><th>Required</th><th>Status</th></tr></thead><tbody>{m.dates.map(d=>{const state=m.error?"unverified":d.status||"scheduled";const Icon=state==="met"?CheckCircle2:["below_target","no_record","needs_review"].includes(state)?AlertCircle:Clock3;return <tr key={d.date}><td><time dateTime={d.date}><strong>{new Date(d.date+"T00:00:00Z").toLocaleDateString(undefined,{day:"numeric",month:"short",timeZone:"UTC"})}</strong><small>{new Date(d.date+"T00:00:00Z").toLocaleDateString(undefined,{weekday:"long",year:"numeric",timeZone:"UTC"})}</small></time></td><td className="mar-duration">{d.recorded_minutes===null?"—":hours(d.recorded_minutes)}</td><td className="mar-required-duration">{hours(d.required_minutes)}</td><td><span className={"mar-day-status status-"+state}><Icon size={14}/>{m.error?"Unverified":statusLabel[state]}</span></td></tr>})}</tbody></table>{!m.dates.length&&<p className="mar-no-dates">No required dates assigned this month.</p>}</div>
 <footer className="mar-detail-footer"><span>Extra hours apply only to the date they were recorded.</span>{m.synced&&<span><Clock3 size={12}/>Synced {new Date(m.synced).toLocaleString(undefined,{timeZone:"Asia/Bahrain",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})} · Bahrain</span>}</footer>
 </div></details>)}</div>}</>}
 </section>
}
