import { useEffect, useMemo, useState, Fragment } from 'react';
import { ArrowRight, ArrowUpRight, CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, Search, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { apiFetch } from '../lib/api';
import UserAvatar from './UserAvatar';
import './SupervisorMonthlyMatrix.css';

type Person = { supervisor_user_id: number; full_name: string; nickname: string };
type Board = { id: number; name: string; supervisor_user_id: number; created_at: string; inactive_at?: string; status?: string };
type Meeting = { id: number; board_id: number; supervisor_id: number; title: string; starts_at: string; status: string };
type Evidence = { tasks: { board_id: number; supervisor_id: number; added: number; done: number }[]; participants: { meeting_id: number; name: string; attendance: string }[]; journeys: { supervisor_id: number; id: number; name: string; start: string; end: string }[] };
const date = (value: string) => Date.parse(value.includes('T') ? value : value.replace(' ', 'T') + 'Z');
const currentMonth = () => new Date(Date.now() + 10800000).toISOString().slice(0, 7);
function shiftMonth(month: string, offset: number) { const d = new Date(`${month}-01T00:00:00Z`); d.setUTCMonth(d.getUTCMonth() + offset); return d.toISOString().slice(0, 7); }

export default function SupervisorMonthlyMatrix({ people, boards, avatars, loading, sourceError, revision, personal = false, compact = false }: { people: Person[]; boards: Board[]; avatars: Record<string, string>; loading: boolean; sourceError: string; revision: number; personal?: boolean; compact?: boolean }) {
 const [month, setMonth] = useState(currentMonth), [query, setQuery] = useState(''), [filter, setFilter] = useState('all'), [expanded, setExpanded] = useState<number | null>(personal ? people[0]?.supervisor_user_id ?? null : null);
 const [data, setData] = useState<Evidence | null>(null), [meetings, setMeetings] = useState<Meeting[]>([]), [loadedKey, setLoadedKey] = useState(''), [loadError, setLoadError] = useState('');
 const requestKey = `${month}:${revision}`, busy = loadedKey !== requestKey, error = busy ? '' : loadError;
 useEffect(() => { let alive = true;
  Promise.all([apiFetch(`/admin/reports/monthly?month=${month}`), apiFetch('/admin/meetings')]).then(([report, all]) => { if (alive) { setData(report); setMeetings(all); setLoadError(''); } }).catch(() => { if (alive) setLoadError('Monthly evidence could not load. Use Refresh to try again.'); }).finally(() => { if (alive) setLoadedKey(requestKey); });
  return () => { alive = false; };
 }, [month, revision, requestKey]);
 const start = Date.parse(`${month}-01T00:00:00+03:00`), end = Date.parse(`${shiftMonth(month, 1)}-01T00:00:00+03:00`);
 const inMonth = (value: string) => date(value) >= start && date(value) < end;
 const isCurrent = month === currentMonth();
 const rows = useMemo(() => people.map(person => {
  const owned = boards.filter(b => b.supervisor_user_id === person.supervisor_user_id && date(b.created_at) < end && (!b.inactive_at || date(b.inactive_at) >= start));
  const projects = owned.map(b => ({ ...b, tasks: data?.tasks.find(t => t.board_id === b.id), meetings: meetings.filter(m => m.board_id === b.id && date(m.starts_at) >= start && date(m.starts_at) < end) }));
  const passed = projects.filter(b => b.meetings.filter(m => m.status === 'completed').length >= 4).length;
  const opened = owned.filter(b => date(b.created_at) >= start).length;
  const closed = owned.filter(b => b.inactive_at && date(b.inactive_at) >= start && date(b.inactive_at) < end).length;
  const tasks = projects.reduce((sum, b) => ({ added: sum.added + (b.tasks?.added || 0), done: sum.done + (b.tasks?.done || 0) }), { added: 0, done: 0 });
  const activeBoards = projects.filter(b => (b.tasks?.added || 0) > 0 && (b.tasks?.done || 0) > 0).length;
  const journeys = data?.journeys.filter(t => t.supervisor_id === person.supervisor_user_id) || [];
  const moved = journeys.filter(t => t.start && t.end && t.start !== t.end).length;
  const meets = owned.length > 0 && passed === owned.length;
  const status = !owned.length ? 'No projects' : (!meets || projects.some(b => !b.tasks?.added)) ? (isCurrent ? 'In progress' : 'Needs attention') : activeBoards < owned.length ? 'Needs verification' : 'On track';
  const belowMeetingTarget = projects.length - passed;
  const missingCards = projects.filter(b => b.tasks && b.tasks.added === 0).length;
  const missingCompletions = projects.filter(b => b.tasks && b.tasks.done === 0).length;
  const missingEvidence = projects.filter(b => !b.tasks).length;
  const boardLabel = (count: number) => `${count} board${count === 1 ? '' : 's'}`;
  const reasons = [
   ...(belowMeetingTarget ? [`${boardLabel(belowMeetingTarget)} below 4 completed meetings`] : []),
   ...(missingCards ? [`${boardLabel(missingCards)} with no cards added`] : []),
   ...(missingCompletions ? [`${boardLabel(missingCompletions)} with no recorded task completion — verify history`] : []),
   ...(missingEvidence ? [`Task evidence unavailable for ${boardLabel(missingEvidence)}`] : []),
  ];
  if (!projects.length) reasons.push('No project boards recorded for this month.');
  else if (!reasons.length) reasons.push('Every board meets all three requirements.');
  return { ...person, reasons, projects, passed, opened, closed, working: owned.length - closed, tasks, activeBoards, journeys, moved, status };
 }), [people, boards, meetings, data, start, end, isCurrent]);
 const visible = rows.filter(r => `${r.full_name} ${r.nickname}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (filter === 'met' ? r.status === 'On track' : r.status !== 'On track')));
 const unavailable = busy || loading || !!error || !!sourceError;
 const totalMeetings = meetings.filter(m => inMonth(m.starts_at) && m.status === 'completed').length;
 if (compact) {
  const row = rows[0];
  return <section className="monthly-matrix mm-dashboard-card" aria-label="Your monthly performance">
   <header className="mm-dash-heading"><div><span className="mm-eyebrow"><ShieldCheck size={14}/> YOUR MONTHLY STATUS</span><div className="mm-dash-title"><h2>{new Date(`${month}-01T12:00:00Z`).toLocaleDateString('en-GB', { month: 'long', year: 'numeric' })}</h2>{!unavailable && row && <span className="mm-badge" data-status={row.status}><span className="mm-status-dot"/>{row.status}</span>}</div></div><Link className="mm-report-link" to="/admin/reports">View my report <ArrowUpRight size={16}/></Link></header>
   {unavailable && <p className="mm-dash-loading" role={error || sourceError ? 'alert' : 'status'}>{error || sourceError || 'Loading your monthly status…'}</p>}
  </section>;
 }
 return <section className="monthly-matrix" aria-label="Monthly supervisor performance">
  <header className="mm-header"><div><span className="mm-eyebrow"><ShieldCheck size={14}/> MONTHLY ACCOUNTABILITY</span><h2>{personal ? 'Your monthly report' : 'Supervisor performance'}</h2><p>{personal ? 'Your check-ins, board activity, and the next steps for each project.' : 'A clear view of the check-ins, work, and people behind every project.'}</p></div><div className="mm-month"><button aria-label="Previous report month" onClick={() => setMonth(shiftMonth(month, -1))}><ChevronLeft size={17}/></button><label><CalendarDays size={16}/><input type="month" aria-label="Report month" value={month} max={currentMonth()} onChange={e => { if (/^\d{4}-\d{2}$/.test(e.target.value) && e.target.value <= currentMonth()) setMonth(e.target.value); }}/></label><button aria-label="Next report month" disabled={isCurrent} onClick={() => setMonth(shiftMonth(month, 1))}><ChevronRight size={17}/></button></div></header>
  <div className="mm-period"><span>{isCurrent ? 'MONTH IN PROGRESS' : 'MONTHLY REVIEW'}</span> Bahrain time · {isCurrent ? 'Results so far; targets apply to the full month.' : 'Based on retained records; later edits can affect results.'}</div>
  <div className="mm-stats">{[[personal ? 'Your project boards' : 'Supervisors', personal ? rows[0]?.projects.length || 0 : people.length, 'In this review'], ['Meeting target met', rows.filter(r => r.projects.length && r.passed === r.projects.length).length, '4 completed per project'], ['Completed meetings', totalMeetings, 'Across this month'], ['Boards closed', rows.reduce((n, r) => n + r.closed, 0), 'Marked inactive this month']].map(([label, value, note]) => <div key={label}><span>{label}</span><strong>{unavailable ? '—' : value}</strong><small>{note}</small></div>)}</div>
  <details className="mm-rules"><summary><ShieldCheck size={16}/> Review rules <span>4 meetings + card activity / board</span><ChevronDown size={15}/></summary><div><p><strong>Meetings:</strong> at least four marked completed for every board active during the month. Scheduled or cancelled meetings do not count. Partial months are not prorated.</p><p><strong>Boards & tasks:</strong> board openings and closures are informational. Every board must have at least one card added and one task marked done during the month. Counts include activity by the board’s team. Closed means marked inactive, not necessarily successfully completed.</p><p><strong>Overall status:</strong> On track means every board meets all three rules. Missing completion history is flagged for verification. Talent movement is shown as context, not a performance rule.</p></div></details>
  <details className="mm-status-guide"><summary>What do the statuses mean?</summary><dl>
   <div><dt><span className="mm-badge" data-status="On track">On track</span></dt><dd>Every board has 4 completed meetings, at least 1 card added, and at least 1 recorded task completion.</dd></div>
   <div><dt><span className="mm-badge" data-status="In progress">In progress</span></dt><dd>The current month is still open. Some boards still need completed meetings or cards added.</dd></div>
   <div><dt><span className="mm-badge" data-status="Needs attention">Needs attention</span></dt><dd>The month has ended and at least one board has fewer than 4 completed meetings or no cards added. See the reasons under the badge.</dd></div>
   <div><dt><span className="mm-badge" data-status="Needs verification">Needs verification</span></dt><dd>Meeting and card-creation requirements are met, but at least one board has no recorded task completion. Check its history; older completions may not have been tracked.</dd></div>
   <div><dt><span className="mm-badge" data-status="No projects">No projects</span></dt><dd>No boards were recorded for this supervisor in the selected month. Performance is not assessed.</dd></div>
  </dl><p>Board openings, closures, and talent movement do not affect the overall status.</p></details>
  {!personal && <div className="mm-toolbar"><div className="mm-tabs">{[['all', 'All supervisors'], ['review', 'To review'], ['met', 'On track']].map(([key, label]) => <button key={key} aria-pressed={filter === key} onClick={() => setFilter(key)}>{label}</button>)}</div><label className="mm-search"><Search size={16}/><input aria-label="Search monthly supervisors" placeholder="Find a supervisor…" value={query} onChange={e => setQuery(e.target.value)}/></label></div>}
  {unavailable ? <div className="mm-empty" role={error || sourceError ? 'alert' : 'status'}>{error || sourceError || 'Loading monthly supervisor evidence…'}</div> : <div className="mm-scroll"><table><thead><tr><th>Supervisor</th><th>Overall status</th><th>Meetings</th><th>Boards</th><th>Tasks</th><th>Talent movement</th><th><span className="mm-sr">Details</span></th></tr></thead><tbody>{visible.map(r => <Fragment key={r.supervisor_user_id}><tr><td><div className="mm-person"><UserAvatar src={avatars[r.nickname?.toLowerCase()]} alt={r.full_name} fallback={r.full_name.slice(0, 2)} sizeClass="h-10 w-10"/><div><strong>{r.full_name}</strong><small>{r.projects.length} project{r.projects.length === 1 ? '' : 's'} this month</small></div></div></td><td className="mm-status-cell"><span className="mm-badge" data-status={r.status}>{r.status === 'On track' && <Check size={13}/>} {r.status}</span><ul className="mm-status-reasons" aria-label={`Status reasons for ${r.full_name}`}>{r.reasons.map(reason => <li key={reason}>{reason}</li>)}</ul>{r.projects.length > 0 && <button className="mm-reason-link" aria-expanded={expanded === r.supervisor_user_id} onClick={() => setExpanded(expanded === r.supervisor_user_id ? null : r.supervisor_user_id)}>{expanded === r.supervisor_user_id ? 'Hide board details' : 'See reasons by board'}<ChevronDown size={12}/></button>}</td><td><strong>{r.passed} / {r.projects.length}</strong><small>projects meet minimum</small><progress aria-label={`${r.full_name}: projects meeting minimum`} value={r.passed} max={r.projects.length || 1}/></td><td><strong>{r.opened} opened · {r.closed} closed</strong><small>{r.working} {isCurrent ? 'still active' : 'active at month end'}*</small></td><td><strong>{r.tasks?.added ?? '—'} added</strong><small>{r.tasks?.done ?? '—'} recorded completions*</small><small>{r.activeBoards} / {r.projects.length} boards meet activity rule</small></td><td><strong>{r.moved} board changes</strong><small>Project progress unverified</small></td><td><button className="mm-expand" aria-label={`Review ${r.full_name}`} aria-expanded={expanded === r.supervisor_user_id} onClick={() => setExpanded(expanded === r.supervisor_user_id ? null : r.supervisor_user_id)}><ChevronDown size={18}/></button></td></tr>{expanded === r.supervisor_user_id && <tr><td colSpan={7} className="mm-detail"><div className="mm-detail-grid"><div><h3>Board requirements <span>3 checks per board</span></h3>{!r.projects.length && <p>No project boards recorded for this month.</p>}{r.projects.map(b => { const completed = b.meetings.filter(m => m.status === 'completed').length; return <article key={b.id} className="mm-project"><header><Link to={`/admin/boards/${b.id}`}>{b.name}<ArrowUpRight size={14}/></Link><span className="mm-badge" data-status={completed >= 4 ? 'Target met' : isCurrent ? 'In progress' : 'Needs attention'}>{completed} / 4 completed</span></header><ul className="mm-board-requirements" aria-label={`Requirements for ${b.name}`}>
 <li data-result={completed >= 4 ? 'met' : 'missing'}><strong>{completed >= 4 ? '✓' : '○'} Meetings · {completed} / 4 completed</strong><span>{completed >= 4 ? 'Meeting minimum met.' : `${4 - completed} more completed meeting${4 - completed === 1 ? '' : 's'} ${isCurrent ? 'needed this month' : 'were needed to meet the monthly minimum'}.`}</span></li>
 <li data-result={(b.tasks?.added || 0) > 0 ? 'met' : 'missing'}><strong>{(b.tasks?.added || 0) > 0 ? '✓' : '○'} Cards added · {b.tasks?.added ?? '—'}</strong><span>{!b.tasks ? 'Task evidence is unavailable.' : b.tasks.added > 0 ? 'Card-creation requirement met.' : 'No cards added this month. Minimum: 1 per board.'}</span></li>
 <li data-result={(b.tasks?.done || 0) > 0 ? 'met' : 'verify'}><strong>{(b.tasks?.done || 0) > 0 ? '✓' : '?'} Tasks completed · {b.tasks?.done ?? '—'} recorded</strong><span>{!b.tasks ? 'Task evidence is unavailable.' : b.tasks.done > 0 ? 'Task-completion requirement met.' : 'No completion recorded this month. Minimum: 1. Verify history because older completions may not have been tracked.'}</span></li>
 </ul>{!b.meetings.length ? <p>No meetings recorded this month.</p> : b.meetings.sort((a, b) => date(a.starts_at) - date(b.starts_at)).map(m => <div className="mm-meeting" key={m.id}><div><strong>{m.title}</strong><small>{new Date(date(m.starts_at)).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', timeZone: 'Asia/Bahrain' })} · {m.status}</small><small>With: {data?.participants.filter(p => p.meeting_id === m.id).map(p => `${p.name}${p.attendance === 'attended' ? ' (attended)' : ''}`).join(', ') || 'Participants not recorded'}</small></div></div>)}</article>; })}</div><div><h3>Talent journey <span>{isCurrent ? 'Start → now' : 'Start → end'}</span></h3><p>Latest dated board assignment at each boundary. A board change is evidence of reassignment, not verified academic progress.</p>{!r.journeys.length && <p>No talents currently assigned.</p>}{r.journeys.map(t => <div className="mm-journey" key={t.id}><Link to={personal ? `/profile/${t.id}` : `/admin/users/${t.id}/profile`}>{t.name}<ArrowUpRight size={13}/></Link><div><span>{t.start || 'Not recorded'}</span><ArrowRight size={15}/><span>{t.end || 'Not recorded'}</span></div><small>{t.start && t.end && t.start !== t.end ? 'Board changed · verify project progress' : 'No recorded board change'}</small></div>)}</div></div></td></tr>}</Fragment>)}</tbody></table>{!visible.length && <p className="mm-empty">No supervisors match this view.</p>}</div>}
  <footer>* Completion-event tracking starts with this update; older completions cannot be reconstructed. Board history uses retained creation and latest closure dates; reopened or deleted boards can change past results. Talent comparisons use current assignments and retained board memberships. Verified project-stage snapshots are not yet available.</footer>
 </section>;
}
