import { useEffect,useLayoutEffect,useRef } from 'react';
import { textSegments,type TextRun } from '../lib/whiteboardText';
type Props={text:string;runs:TextRun[];placeholder:string;onChange:(text:string)=>void;onSelection:(start:number,end:number)=>void;onBlur:(target:EventTarget|null)=>void;onEscape:()=>void};
function rangeAt(element:HTMLElement,start:number,end:number){const range=document.createRange();const walker=document.createTreeWalker(element,NodeFilter.SHOW_TEXT);let node=walker.nextNode(),offset=0;let setStart=false;while(node){const length=node.textContent?.length||0;if(!setStart&&start<=offset+length){range.setStart(node,Math.max(0,start-offset));setStart=true;}if(end<=offset+length){range.setEnd(node,Math.max(0,end-offset));return range;}offset+=length;node=walker.nextNode();}range.selectNodeContents(element);range.collapse(false);return range;}
export default function WhiteboardTextEditor({text,runs,placeholder,onChange,onSelection,onBlur,onEscape}:Props){
 const ref=useRef<HTMLDivElement>(null);const selection=useRef({start:0,end:0});const callback=useRef(onSelection);useLayoutEffect(()=>{callback.current=onSelection;},[onSelection]);
 useLayoutEffect(()=>{const el=ref.current;if(!el)return;const focused=document.activeElement===el;const nodes=textSegments(text,runs).map(s=>{const span=document.createElement('span');span.textContent=s.text;if(s.textColor&&/^#[0-9a-f]{6}$/i.test(s.textColor))span.style.color=s.textColor;if(s.font)span.style.fontSize=`${s.font}px`;if(s.bold!==undefined)span.style.fontWeight=s.bold?'700':'400';if(s.italic!==undefined)span.style.fontStyle=s.italic?'italic':'normal';return span;});el.replaceChildren(...nodes);if(focused){const r=rangeAt(el,Math.min(selection.current.start,text.length),Math.min(selection.current.end,text.length));const sel=window.getSelection();sel?.removeAllRanges();sel?.addRange(r);}},[text,runs]);
 useEffect(()=>{const el=ref.current;el?.focus({preventScroll:true});function update(){const sel=window.getSelection();if(!el||!sel?.rangeCount)return;const r=sel.getRangeAt(0);if(!el.contains(r.startContainer)||!el.contains(r.endContainer))return;const pre=r.cloneRange();pre.selectNodeContents(el);pre.setEnd(r.startContainer,r.startOffset);const start=pre.toString().length,end=start+r.toString().length;selection.current={start,end};callback.current(start,end);}document.addEventListener('selectionchange',update);return()=>document.removeEventListener('selectionchange',update);},[]);
 function captureSelection(){const el=ref.current,sel=window.getSelection();if(!el||!sel?.rangeCount)return;const r=sel.getRangeAt(0);if(!el.contains(r.startContainer)||!el.contains(r.endContainer))return;const pre=r.cloneRange();pre.selectNodeContents(el);pre.setEnd(r.startContainer,r.startOffset);const start=pre.toString().length,end=start+r.toString().length;selection.current={start,end};callback.current(start,end);}
 function insert(value:string){const el=ref.current,sel=window.getSelection();if(!el||!sel?.rangeCount)return;const range=sel.getRangeAt(0);if(!el.contains(range.commonAncestorContainer))return;range.deleteContents();const node=document.createTextNode(value);range.insertNode(node);range.setStartAfter(node);range.collapse(true);sel.removeAllRanges();sel.addRange(range);captureSelection();onChange(el.textContent||'');}
 return <div ref={ref} className="wb-rich-editor" contentEditable suppressContentEditableWarning role="textbox" aria-label="Edit whiteboard text" aria-multiline="true" data-placeholder={placeholder} onInput={e=>{captureSelection();onChange(e.currentTarget.textContent||'');}} onBlur={e=>onBlur(e.relatedTarget)} onPaste={e=>{e.preventDefault();insert(e.clipboardData.getData('text/plain'));}} onKeyDown={e=>{if(e.key==='Escape')onEscape();else if(e.key==='Enter'){e.preventDefault();insert('\n');}}}/>;
}
