import RustPiscineReport from './RustPiscineReport';
import ProjectDistribution from './ProjectDistribution';
import { useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { apiFetch } from '../lib/api';
import UserAvatar from '../components/UserAvatar';
type Person={supervisor_user_id:number;full_name:string;nickname:string};
type Board={id:number;name:string;lists_count?:number;supervisor_name:string};
type Meeting={id:number;supervisor_id:number;status:string;starts_at:string;title:string};
type Talent={id:number;full_name:string;nickname:string;role:string;cohort?:string;assigned_boards?:string[]};
export default function ReportInsights({boards,people,avatars,done,cards,complete,revision}:{boards:Board[];people:Person[];avatars:Record<string,string>;done:number;cards:number;complete:boolean;revision:number}){
 const [meetings,setMeetings]=useState<Meeting[]>([]),[users,setUsers]=useState<Talent[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState('');
 const [week,setWeek]=useState(0);
 useEffect(()=>{let alive=true;setBusy(true);setError('');Promise.all([apiFetch('/admin/meetings'),apiFetch('/admin/users?role=all&q=')]).then(([m,u])=>{if(alive){setMeetings(Array.isArray(m)?m:[]);setUsers(Array.isArray(u)?u:[]);}}).catch(()=>{if(alive)setError('Meeting and talent insights could not load. Refresh to retry.');}).finally(()=>{if(alive)setBusy(false);});return()=>{alive=false;};},[revision]);
 const now=new Date();const bahrainDay=new Date(now.getTime()+3*60*60*1000);const start=new Date(Date.UTC(bahrainDay.getUTCFullYear(),bahrainDay.getUTCMonth(),bahrainDay.getUTCDate()-bahrainDay.getUTCDay()-week*7)-3*60*60*1000);const end=new Date(start.getTime()+7*86400000);const dayLabel=(d:Date)=>d.toLocaleDateString('en-GB',{timeZone:'Asia/Bahrain'});
 const weekly=meetings.filter(m=>new Date(m.starts_at)>=start&&new Date(m.starts_at)<end);
 const ranking=people.map(p=>({...p,count:weekly.filter(m=>m.supervisor_id===p.supervisor_user_id&&m.status==='completed').length,scheduled:weekly.filter(m=>m.supervisor_id===p.supervisor_user_id&&m.status==='scheduled').length})).sort((a,b)=>b.count-a.count||a.full_name.localeCompare(b.full_name));
 const upcoming=meetings.filter(m=>m.status==='scheduled'&&new Date(m.starts_at)>=now);
 const talents=users.filter(u=>u.role==='student'); const stats=[['Completion',complete?(cards?`${Math.round(done/cards*100)}%`:'—'):'—',`${done} / ${cards} tasks done`],['Boards',boards.length,`${boards.reduce((a,b)=>a+(b.lists_count||0),0)} lists`],['Talents',talents.length,`${people.length} supervisors`],['Meetings',meetings.length,`${meetings.filter(m=>m.status==='completed').length} completed`],['Upcoming',upcoming.length,`${upcoming.filter(m=>dayLabel(new Date(m.starts_at))===dayLabel(now)).length} today`]];
 return <>{error&&<p role="alert">{error}</p>}<div className="insight-stats">{stats.map(([label,value,note])=><div key={label}><span>{label}</span><strong>{busy||error?'—':value}</strong><small>{busy?'Loading…':note}</small></div>)}</div>
 <section className="insight-week"><header><div><span>WEEKLY MEETING REVIEW</span><h2>Who’s checking in?</h2><p>{dayLabel(start)} – {dayLabel(new Date(end.getTime()-1))} · {week===0?'Week in progress':'Previous week'}</p></div><div><button aria-label="Previous meeting week" onClick={()=>setWeek(w=>w+1)}><ChevronLeft size={18}/></button><button disabled={!week} onClick={()=>setWeek(0)}>This week</button><button disabled={!week} aria-label="Next meeting week" onClick={()=>setWeek(w=>w-1)}><ChevronRight size={18}/></button></div></header><p className="insight-note">Ranked by meetings marked completed, using their scheduled date. History uses saved meeting records and reflects later edits.</p>
 {busy||error?<p>{error||'Loading meeting history…'}</p>:<div className="insight-week-grid"><div><h3>Meeting ranking</h3>{ranking.map(p=><div className="insight-rank" key={p.supervisor_user_id}><small>{1+ranking.filter(r=>r.count>p.count).length}</small><UserAvatar src={avatars[p.nickname?.toLowerCase()]} alt={p.full_name} fallback={p.full_name.slice(0,2)} sizeClass="h-8 w-8"/><span>{p.full_name}</span><strong>{p.count}<small>completed</small></strong></div>)}</div><div className="insight-missing"><h3>{week===0?'No completed meeting yet':'No completed meeting'} <span>{ranking.filter(p=>!p.count).length}</span></h3><p>At least one completed meeting per supervisor per week.</p>{ranking.filter(p=>!p.count).map(p=><div key={p.supervisor_user_id}><UserAvatar src={avatars[p.nickname?.toLowerCase()]} alt={p.full_name} fallback={p.full_name.slice(0,2)} sizeClass="h-8 w-8"/><span>{p.full_name}<small>{p.scheduled} scheduled in this week</small></span></div>)}{ranking.every(p=>p.count>0)&&<p>Every supervisor has a completed meeting.</p>}</div></div>}</section>
 <RustPiscineReport users={users} loading={busy} error={error}/><ProjectDistribution boards={boards} users={users} avatars={avatars} loading={busy} error={error}/></>;
}
