import { useState } from 'react';
import { Link } from 'react-router-dom';
import { GraduationCap, Search, CheckCircle2, XCircle, Clock3, CircleDashed, CircleHelp } from 'lucide-react';
import { useRustPiscineFilter } from '../components/RustPiscineFilter';
type Talent={id:number;full_name:string;nickname:string;role:string;cohort?:string};
const categories=[{key:'passed',label:'Passed',Icon:CheckCircle2},{key:'failed',label:'Failed',Icon:XCircle},{key:'working',label:'Working',Icon:Clock3},{key:'not_started',label:'No record',Icon:CircleDashed},{key:'unknown',label:'Unavailable',Icon:CircleHelp}];
export default function RustPiscineReport({users,loading,error}:{users:Talent[];loading:boolean;error:string}){
 const filter=useRustPiscineFilter();const [query,setQuery]=useState(''),[cohort,setCohort]=useState('all');
 const talents=users.filter(u=>u.role==='student');const cohorts=[...new Set(talents.map(u=>u.cohort).filter(Boolean))].sort();
 const scoped=talents.filter(u=>cohort==='all'||u.cohort===cohort);const status=(u:Talent)=>filter.statuses[u.nickname?.toLowerCase()]||'unknown';
 const visible=scoped.filter(u=>(filter.value==='all'||status(u)===filter.value)&&`${u.full_name} ${u.nickname}`.toLowerCase().includes(query.toLowerCase()));const busy=loading||filter.loading;const failure=error||filter.error;
 return <section className="insight-distribution rust-report"><header><div><span>LEARNING PROGRESS</span><h2><GraduationCap size={24}/> Rust piscine</h2><p>Talents only. Passing any attempt counts as passed; otherwise the latest attempt is shown.</p></div><label>Cohort<select value={cohort} onChange={e=>setCohort(e.target.value)}><option value="all">All cohorts</option>{cohorts.map(c=><option key={c}>{c}</option>)}</select></label></header><div className="rust-summary">{categories.map(({key,label,Icon})=><button key={key} data-status={key} disabled={busy||!!failure} aria-pressed={filter.value===key} onClick={()=>filter.setValue(filter.value===key?'all':key)}><Icon size={18}/><strong>{busy||failure?'—':scoped.filter(u=>status(u)===key).length}</strong><span>{label}</span></button>)}</div><div className="rust-controls"><label className="reports-search"><Search size={16}/><input aria-label="Search Rust piscine talents" placeholder="Find a talent…" value={query} onChange={e=>setQuery(e.target.value)}/></label><button onClick={()=>{filter.setValue('all');setQuery('');setCohort('all');}}>Show all talents</button></div>{busy?<p role="status">Loading Rust piscine results…</p>:failure?<p role="alert">{failure}</p>:<><p>{visible.length} matching talents · No record means no Rust piscine progress was returned by Reboot.</p><div className="rust-people">{visible.map(u=>{const meta=categories.find(c=>c.key===status(u))!;return <Link to={`/admin/users/${u.id}/profile`} key={u.id}><span><strong>{u.full_name}</strong><small>@{u.nickname} · {u.cohort||'No cohort'}</small></span><span data-status={meta.key}><meta.Icon size={15}/>{meta.label}</span></Link>;})}{!visible.length&&<p>No talents match these filters.</p>}</div></>}</section>;
}
