import { test } from 'node:test';
import assert from 'node:assert/strict';
import { cachedProfileResource, peekProfileCache, clearProfileCache, PROFILE_CACHE_TTL, profileFetchesRemaining } from './profileCache.ts';
const storage = () => { const values = new Map(); return { getItem: k => values.get(k) ?? null, setItem: (k,v) => values.set(k,v), removeItem: k => values.delete(k) }; };
globalThis.localStorage = storage(); globalThis.sessionStorage = storage();
localStorage.setItem('email','one@example.test');
const settle = () => new Promise(resolve => setImmediate(resolve));
test('cache lifecycle, force sync, failure retention, concurrency, and account isolation', async () => {
 clearProfileCache();
 let calls = 0;
 const loader = async () => ({ count: ++calls });
 assert.equal((await cachedProfileResource('p',loader)).count,1);
 assert.equal((await cachedProfileResource('p',loader)).count,1);
 await settle();
 assert.equal((await cachedProfileResource('p',loader,true)).count,2);
 await settle();
 const realNow = Date.now; const now = realNow(); Date.now = () => now + PROFILE_CACHE_TTL + 1;
 assert.equal((await cachedProfileResource('p',loader)).count,3);
 Date.now = realNow; await settle();
 await assert.rejects(cachedProfileResource('p',async () => {throw new Error('offline');},true));
 assert.equal(peekProfileCache('p').value.count,3); await settle();
 const releases=[]; let started=0;
 const jobs=Array.from({length:5},(_,i)=>cachedProfileResource(`queue-${i}`,()=>{started++;return new Promise(resolve=>releases.push(resolve));}));
 const duplicate=cachedProfileResource('queue-0',async()=>{throw new Error('duplicate request');});
 await settle();assert.equal(started,3);assert.equal(profileFetchesRemaining(),5);
 releases.shift()('ok');await settle();assert.equal(started,4);
 releases.shift()('ok');await settle();assert.equal(started,5);
 for(const release of releases)release('ok');await Promise.all([...jobs,duplicate]);await settle();assert.equal(profileFetchesRemaining(),0);
 localStorage.setItem('email','two@example.test');assert.equal(peekProfileCache('p'),undefined);
 let finish;const old=cachedProfileResource('old',()=>new Promise(resolve=>{finish=resolve;}));await settle();
 clearProfileCache();finish('private');await old;await settle();assert.equal(peekProfileCache('old'),undefined);
});
